services:
  experience_mongo:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-mongodb:v0.0.6
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $EXPERIENCE_MONGO_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: $EXPERIENCE_MONGO_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      OTEL_SERVICE_NAME: $EXPERIENCE_MONGO_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "8081"
        protocol: tcp
