services:
  sales_salespg:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.salespg
    environment:
      CONNECTION_URI: $SALES_SALESPG_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $SALES_SALESPG_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $SALES_SALESPG_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $SALES_SALESPG_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - mode: ingress
        protocol: tcp
        published: "9464"
        target: 8080
