services:
  sales_ts:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    develop:
      watch:
        - path: package.json
          action: rebuild
          target: /functions/package.json
        - path: package-lock.json
          action: rebuild
          target: /functions/package-lock.json
        - path: ./
          action: sync+restart
          target: /functions
    environment:
      HASURA_CONNECTOR_PORT: $SALES_TS_HASURA_CONNECTOR_PORT
      HASURA_SERVICE_TOKEN_SECRET: $SALES_TS_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: $SALES_TS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      OTEL_SERVICE_NAME: $SALES_TS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "8081"
        protocol: tcp
