services:
  sales_salests:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $SALES_SALESTS_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $SALES_SALESTS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $SALES_SALESTS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - mode: ingress
        protocol: tcp
        published: "9037"
        target: 8080
