services:
  users_clickhouse:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.clickhouse
    environment:
      CLICKHOUSE_PASSWORD: $USERS_CLICKHOUSE_CLICKHOUSE_PASSWORD
      CLICKHOUSE_URL: $USERS_CLICKHOUSE_CLICKHOUSE_URL
      CLICKHOUSE_USERNAME: $USERS_CLICKHOUSE_CLICKHOUSE_USERNAME
      HASURA_SERVICE_TOKEN_SECRET: $USERS_CLICKHOUSE_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $USERS_CLICKHOUSE_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $USERS_CLICKHOUSE_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - mode: ingress
        protocol: tcp
        published: "9448"
        target: 8080
